### PR TITLE
Increase max result limit for longer history

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by ojousima** [comment]
Current 10k limit has about 52 days of history in mixed mode. 144k is probably more than necessary, ~750 days assuming 52 days / 10k. It's not an overkill though.

**Comment by DG12** [comment]
Can you please detail your calculation.

**Comment by ojousima** [comment]
52 days is based on observed bug where older data doesn't get returned, rest of it is calculated from that and current limit.

**Comment by DG12** [comment]
1) WIth what APP_LOG_INTERVAL_S  ?
2) Is that dependent on saving   temp, humidity and pressure?

**Comment by ojousima** [comment]
> WIth what APP_LOG_INTERVAL_S ?
Is that dependent on saving temp, humidity and pressure?

This is unrelated to Ruuvi Firmware, number of data points relates to density of sparse storage

**Comment by DG12** [comment]
I'd like to understand better can you direct me to a reference?

**Comment by ojousima** [comment]
We don't have reference materials for the internals for the Cloud at this time

**Review by Muhwu — APPROVED** [review]

**Pull request merged**
