### PR TITLE
Add Semistandard action

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by ojousima** [comment]
Checking that GH action works as intended

**Comment by ojousima** [comment]
The rest of the errors need to be checked manually, I'll work it on Monday

**Comment by ojousima** [comment]
redisHelper.js:24 has a return statements in try-catch-finally, catch block return will never get executed. What's the intended operation?

**Comment by ojousima** [comment]
setUserSetting:executeSetUserSetting() needs to be looked over. Undefined variable used for checking db action result in error, no default action on updated rows.

**Comment by ojousima** [comment]
8496a02 needs to be looked over, it seems that not initializing "threw" variable masks error in integration test.

**Comment by ojousima** [comment]
The rest of the issues need a manual review.
```
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/Helpers/redisHelper.js:24:5: Unsafe usage of ReturnStatement.
6
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/setUserSetting.js:33:9: 'results' is not defined.
7
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/setUserSetting.js:33:33: 'results' is not defined.
8
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/setUserSetting.js:34:42: 'HTTPCodes' is not defined.
9
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/setUserSetting.js:36:40: 'HTTPCodes' is not defined.
10
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/shareSensor.js:35:5: Unsafe usage of ReturnStatement.
11
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/UserApi/uploadSensorPicture.js:57:7: Unsafe usage of ReturnStatement.
12
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/tests/integration/alerts.test.js:337:7: 'threw' is not defined.
13
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/tests/integration/alerts.test.js:340:12: 'threw' is not defined.
14
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/tests/integration/alerts.test.js:675:7: 'threw' is not defined.
15
  /home/runner/work/ruuvi-network-serverless/ruuvi-network-serverless/tests/integration/alerts.test.js:678:12: 'threw' is not defined.
```
We can go through these at the next meeting

**Review by Muhwu — APPROVED** [review]

**Pull request merged**
